Magic Poi Lite: Loading Class Reference
Loading Class Reference
Public Member Functions
Loading ()
Default constructor for Loading class.
String getTimelineNumber ()
Retrieves the current timeline number from the server.
bool getTimeline (String tln)
Retrieves the timeline data from the server based on the specified timeline number.
void saveTimeline (const String &timelineData)
Saves the timeline data to a file.
bool load ()
Loads data required for the application.
Private Attributes
WiFiClient client
WiFi client object.
Authentication authentication
Authentication object.
char token [512]
JWT token buffer.
String timelineNumber = "0"
Default timeline number.
String timelineFilePath = "/timeline" + timelineNumber + ".txt"
File path of the timeline file.
Constructor & Destructor Documentation
Loading()
Loading::Loading ()
Default constructor for Loading class.
This constructor initializes the Loading object. It attempts to load a JWT token from a file using the Authentication object. If a token is successfully loaded, it is stored internally. Otherwise, it prepares to use password login if token loading fails.
{
    // token = authentication.readJWTTokenFromFile(); //todo: add logic to use Password login if this fails
    String savedToken = authentication.readJWTTokenFromFile();
    if (!savedToken.isEmpty())
    {
        strncpy(token, savedToken.c_str(), sizeof(token) - 1);
        token[sizeof(token) - 1] = '\0'; // Null-terminate the token string
        // strncpy(jwtToken, savedToken.c_str(), sizeof(jwtToken) - 1);
        // jwtToken[sizeof(jwtToken) - 1] = '\0'; // Null-terminate the token string
        // gotToken = true;
        Serial.println("Using saved JWT token:");
        Serial.println(token);
    }
}
References authentication, Authentication::readJWTTokenFromFile(), and token.
Member Function Documentation
getTimeline()
bool Loading::getTimeline (String tln)
Retrieves the timeline data from the server based on the specified timeline number.
This method sends a GET request to the server to retrieve the timeline data corresponding to the provided timeline number. It includes the JWT token in the request headers for authentication. If the request is successful and the response code is OK, the timeline data is saved and the method returns true. If any error occurs during the HTTP request or the response code indicates a failure, the method returns false.
Parameters
tln The timeline number to retrieve data for.
Returns
true if the timeline data is successfully retrieved, false otherwise.
{
    HTTPClient http;
    http.begin(client, "http://" + String(serverIP) + ":" + String(serverPort) + "/lite/api/load-timeline?number=" + tln);
    http.addHeader("Authorization", "Bearer " + String(token));
    Serial.println("[HTTP] GET...");
    int httpCode = http.GET();
    // httpCode will be negative on error
    if (httpCode > 0)
    {
        if (httpCode == HTTP_CODE_OK)
        {
            // Print the API response
            // DynamicJsonDocument led_doc(1500);
            String payload = http.getString();
            saveTimeline(payload);
            Serial.println("got Timeline: ");
            Serial.println(payload);
            // delay(10);
            // loadTimeline();
            // already_got_data = true;
            // digitalWrite(led, LOW);
            http.end();
            return true;
        }
        else
        {
            Serial.print("Failed to get Timeline - Error Code: ");
            Serial.println(httpCode);
            // gotToken=false;
        }
    }
    else
    {
        Serial.println("Connection failed.");
        // gotToken=false;
    }
    http.end();
    return false;
}
References client, saveTimeline(), and token.
Referenced by load().
getTimelineNumber()
String Loading::getTimelineNumber ()
Retrieves the current timeline number from the server.
This method sends a GET request to the server to retrieve the current timeline number. It includes the JWT token in the request headers for authentication. If the request is successful and the response code is OK, the method returns the timeline number received from the server. If any error occurs during the HTTP request or the response code indicates a failure, an empty string is returned.
Returns
A string containing the current timeline number, or an empty string if the request fails or if the server response code is not OK.
{
    HTTPClient http;
    http.begin(client, "http://" + String(serverIP) + ":" + String(serverPort) + "/lite/api/get-current-timeline-number");
    http.addHeader("Authorization", "Bearer " + String(token));
    Serial.println("[HTTP] GET...");
    int httpCode = http.GET();
    String response = "";
    // httpCode will be negative on error
    if (httpCode > 0)
    {
        if (httpCode == HTTP_CODE_OK)
        {
            // Print the API response
            response = http.getString();
            Serial.print("Got timeline number: ");
            Serial.println(response);
        }
        else
        {
            Serial.print("Failed to get Timeline Number - Error code: ");
            Serial.println(httpCode);
        }
    }
    else
    {
        Serial.println("Connection failed.");
    }
    http.end();
    return response;
}
References client, and token.
Referenced by load().
load()
bool Loading::load ()
Loads data required for the application.
This method attempts to load data required for the application. It first tries to retrieve the current timeline number from the server. If successful, it proceeds to load the timeline data. If both operations succeed, the method returns true indicating successful loading. If any of the operations fail, the method returns false.
Returns
true if data loading is successful, false otherwise.
{
    //todo: load saved timeline if not able to access internet or auth doesn't work?
    Serial.println("Loading data...");
    //load from api:
    timelineNumber = getTimelineNumber();
    if(getTimeline(timelineNumber)){
        return true;
    }
    return false;
}
References getTimeline(), getTimelineNumber(), and timelineNumber.
Referenced by handleAuthenticationAndLoading().
saveTimeline()
void Loading::saveTimeline (const String & timelineData)
Saves the timeline data to a file.
This method saves the provided timeline data to a file using the LittleFS (Little File System). If LittleFS initialization succeeds and the file is successfully created and written, a success message is printed to the Serial monitor. If there's any failure during the file system operation, the method returns without saving the data.
Parameters
timelineData The timeline data to be saved to the file.
{
    if (LittleFS.begin())
    {
        File file = LittleFS.open(timelineFilePath, "w");
        if (file)
        {
            file.print(timelineData);
            file.close();
            Serial.println("Timeline data saved to file.");
        }
        LittleFS.end();
    }
}
References timelineFilePath.
Referenced by getTimeline().
Member Data Documentation
authentication
Authentication Loading::authentication private
Authentication object.
This object is used for handling authentication operations.
Referenced by Loading().
client
WiFiClient Loading::client private
WiFi client object.
This object is used for network communication with the server.
Referenced by getTimeline(), and getTimelineNumber().
timelineFilePath
String Loading::timelineFilePath = "/timeline" + timelineNumber + ".txt" private
File path of the timeline file.
This string represents the file path of the timeline data file, saved in LittleFS.
Referenced by saveTimeline().
timelineNumber
String Loading::timelineNumber = "0" private
Default timeline number.
This string represents the default timeline number used for file paths.
Referenced by load().
token
char Loading::token[512] private
JWT token buffer.
This buffer stores the JWT token retrieved from authentication.
Referenced by getTimeline(), getTimelineNumber(), and Loading().
The documentation for this class was generated from the following files:
src/Loading.h
src/Loading.cpp