Magic Poi Lite: src/Main.cpp File Reference
Main.cpp File Reference
Main program file.
#include <Arduino.h>
#include <ESP8266WiFi.h>
#include <ESP8266WiFiMulti.h>
#include <EEPROM.h>
#include "secrets.h"
#include "Authentication.h"
#include "Loading.h"
#include "Playing.h"
Macros
#define led D4
Pin number for the built-in LED.
Functions
void ICACHE_RAM_ATTR handleUpdateInterrupt ()
Interrupt service routine for handling update button press.
void handleAuthenticationAndLoading ()
Handles authentication and loading of timeline data.
void setup ()
Sets up the system including WiFi connection, authentication, and loading and playing timeline data.
void loop ()
Main loop of the program.
Variables
Authentication authentication
Instance of the Authentication class.
Loading loading
Instance of the Loading class.
Playing playing
Instance of the Playing class.
const int blueLEDPin = D5
Pin number for the blue LED.
const int greenLEDPin = D6
Pin number for the green LED.
const int redLEDPin = D7
Pin number for the red LED.
const int btnUpdatePin = D1
Pin number for the update Button.
const int btnStartPin = D2
Pin number for the start Button.
ESP8266WiFiMulti WiFiMulti
WiFi multi-client manager for ESP8266.
volatile bool updateRequested = false
Flag indicating whether an update is requested.
Detailed Description
Main program file.
The main program - includes setup() and loop(). Currently set to connect to Magic Poi Lite API on startup and fetch the current timeline. Then display the timeline on RGB LEDs according to timings.
Macro Definition Documentation
led
#define led D4
Pin number for the built-in LED.
This constant represents the pin number for the built-in LED on the D1 Mini.
Referenced by Playing::processTimelineData(), setup(), and Playing::setup().
Function Documentation
handleAuthenticationAndLoading()
void handleAuthenticationAndLoading ()
Handles authentication and loading of timeline data.
This function performs the process of checking for saved authentication tokens, handling authentication, and loading timeline data. It prints messages to indicate the status of these operations.
{
  Serial.println("Setup: Connection & Authentication");
  bool isAuthenticated = authentication.checkSavedToken();
  isAuthenticated = false; // test re-auth - todo: tie this to a button press - todo: not working without this?
  if (isAuthenticated) {
    Serial.println("Authentication found. Using saved.");
    if (loading.load()) {
      Serial.println("LOADED AND SAVED TIMELINE SUCCESSFULLY");
      if (playing.setup()) {
        Serial.println("SETUP COMPLETE");
      }
    } else {
      Serial.println("LOADING AND SAVING TIMELINE UNSUCCESSFUL");
    }
  } else {
    bool isAuthenticating = authentication.authenticate();
    if (isAuthenticating) {
      isAuthenticated = authentication.checkSavedToken();
      if (isAuthenticated) {
        Serial.println("Authenticated using login success. Should be saved now, using..");
        if (loading.load()) {
          Serial.println("LOADED AND SAVED TIMELINE SUCCESSFULLY");
          if (playing.setup()) {
            Serial.println("SETUP COMPLETE");
          }
        } else {
          Serial.println("LOADING AND SAVING TIMELINE UNSUCCESSFUL");
        }
      } else {
        Serial.println("Auth check saved JWT after password login failed");
      }
    } else {
      Serial.println("Failed to authenticate with password");
    }
  }
}
References Authentication::authenticate(), authentication, Authentication::checkSavedToken(), Loading::load(), loading, playing, and Playing::setup().
Referenced by loop(), and setup().
handleUpdateInterrupt()
void ICACHE_RAM_ATTR handleUpdateInterrupt ()
Interrupt service routine for handling update button press.
This function sets the updateRequested flag to true when the update button is pressed.
{
  updateRequested = true;
}
References updateRequested.
Referenced by setup().
loop()
void loop ()
Main loop of the program.
This function is the main loop of the program. It checks for update requests and calls handleAuthenticationAndLoading() if an update is requested. It also calls the play function to execute the playing process, which involves changing LED colors over time according to the timeline data. Additionally, it adds a delay of 5 seconds between each play iteration to control the timing of the LED color changes.
            {
  if (updateRequested) {
    updateRequested = false;
    handleAuthenticationAndLoading();
  }
  playing.play();
  delay(5000); // Example: Delay for 5 seconds between each play
}
References handleAuthenticationAndLoading(), Playing::play(), playing, and updateRequested.
setup()
void setup ()
Sets up the system including WiFi connection, authentication, and loading and playing timeline data.
This function initializes the system by establishing a WiFi connection, setting up interrupt for update button, and calling handleAuthenticationAndLoading() to handle authentication and loading processes.
             {
  Serial.begin(115200);
  pinMode(led, OUTPUT);
  digitalWrite(led, HIGH); // HIGH is off for D1 mini
  // Set the digital pins as outputs
  pinMode(greenLEDPin, OUTPUT);
  pinMode(redLEDPin, OUTPUT);
  pinMode(blueLEDPin, OUTPUT);
  pinMode(btnUpdatePin, INPUT_PULLUP);
  // WiFi connection
  WiFi.mode(WIFI_STA);
  WiFiMulti.addAP(WIFI_SSID, WIFI_PASSWORD);
  Serial.println("Connecting to WiFi");
  while (WiFiMulti.run() != WL_CONNECTED) {
    Serial.print(".");
    delay(500);
  }
  Serial.println("");
  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());
  // Set up interrupt for update button
  attachInterrupt(digitalPinToInterrupt(btnUpdatePin), handleUpdateInterrupt, FALLING);
  // Handle authentication and loading
  handleAuthenticationAndLoading();
}
References blueLEDPin, btnUpdatePin, greenLEDPin, handleAuthenticationAndLoading(), handleUpdateInterrupt(), led, redLEDPin, and WiFiMulti.
Variable Documentation
authentication
Authentication authentication
Instance of the Authentication class.
This object is used for handling authentication operations.
Referenced by handleAuthenticationAndLoading().
blueLEDPin
const int blueLEDPin = D5
Pin number for the blue LED.
This constant represents the pin number for the blue LED.
Referenced by Playing::changeColours(), and setup().
btnStartPin
const int btnStartPin = D2
Pin number for the start Button.
This constant represents the pin number for the start Button.
btnUpdatePin
const int btnUpdatePin = D1
Pin number for the update Button.
This constant represents the pin number for the update Button. Used for fetching content from the web.
Referenced by setup().
greenLEDPin
const int greenLEDPin = D6
Pin number for the green LED.
This constant represents the pin number for the green LED.
Referenced by Playing::changeColours(), and setup().
loading
Loading loading
Instance of the Loading class.
This object is used for loading timeline data.
Referenced by handleAuthenticationAndLoading().
playing
Playing playing
Instance of the Playing class.
This object is used for playing timeline data.
Referenced by handleAuthenticationAndLoading(), and loop().
redLEDPin
const int redLEDPin = D7
Pin number for the red LED.
This constant represents the pin number for the red LED.
Referenced by Playing::changeColours(), and setup().
updateRequested
volatile bool updateRequested = false
Flag indicating whether an update is requested.
This flag is set to true when an update is requested via the update button interrupt.
Referenced by handleUpdateInterrupt(), and loop().
WiFiMulti
ESP8266WiFiMulti WiFiMulti
WiFi multi-client manager for ESP8266.
This object is used for managing multiple WiFi connections on ESP8266.
Referenced by setup().