Magic Poi Lite: Authentication Class Reference
Authentication Class Reference
Public Member Functions
Authentication ()
Default constructor for Authentication class.
String readJWTTokenFromFile ()
Reads JWT token from a file stored on LittleFS.
void saveJWTTokenToFile (const char *token)
Saves a JWT token to a file on LittleFS.
bool authenticate ()
Authenticates the client with the server.
bool checkSavedToken ()
Checks for a saved JWT token and loads it if available.
Private Attributes
char token [500]
Buffer for JWT token.
char jwtToken [500]
Buffer for JWT token.
boolean gotToken = false
Flag indicating whether a token has been retrieved.
const char * jwtFilePath = "/jwt.txt"
Path to the file storing JWT token.
WiFiClient client
WiFi client object.
Constructor & Destructor Documentation
Authentication()
Authentication::Authentication ()
Default constructor for Authentication class.
This constructor initializes the Authentication object by clearing the jwtToken buffer.
{
    // Initialize variables
    memset(jwtToken, 0, sizeof(jwtToken)); // Clear jwtToken buffer
}
References jwtToken.
Member Function Documentation
authenticate()
bool Authentication::authenticate ()
Authenticates the client with the server.
This method attempts to authenticate the client with the server by sending a POST request to the login endpoint with the provided email and password. If the authentication is successful, the JWT token received from the server is parsed and saved, and the method returns true. If any error occurs during the HTTP request or JSON parsing, or if the server returns an error response code, the method returns false.
Returns
true if the authentication is successful, false otherwise.
{
    Serial.println("Authenticating...");
    HTTPClient http;
    http.begin(client, "http://" + String(serverIP) + ":" + String(serverPort) + "/api/login");
    http.addHeader("Content-Type", "application/json");
    Serial.println("[HTTP] POST...");
    int httpCode = http.POST("{\"email\":\"" + String(email) + "\",\"password\":\"" + String(passwordJwt) + "\"}");
    // httpCode will be negative on error
    if (httpCode > 0)
    {
        if (httpCode == HTTP_CODE_OK || httpCode == HTTP_CODE_CREATED)
        {
            // Parse the response JSON to get the token
            DynamicJsonDocument doc(1024);
            DeserializationError error = deserializeJson(doc, http.getString());
            if (error)
            {
                Serial.println("Failed to parse JSON.");
                return false;
            }
            strcpy(token, doc["token"]);
            Serial.println("Authentication successful.");
            Serial.println(token);
            gotToken = true;
            saveJWTTokenToFile(token); //save for next time, so we won't need to do this again.
            return true;
        }
        else
        {
            Serial.print("[HTTP] Error code: ");
            Serial.println(httpCode);
        }
    }
    else
    {
        Serial.println("Connection failed.");
    }
    http.end();
    return false;
    // bool isAuthenticated = true; // Simulated result
    // return isAuthenticated;
}
References client, gotToken, saveJWTTokenToFile(), and token.
Referenced by setup().
checkSavedToken()
bool Authentication::checkSavedToken ()
Checks for a saved JWT token and loads it if available.
This method checks if a JWT token is saved in a file. If a token is found, it loads the token into the internal token buffer. If no token is found, the method returns false.
Returns
true if a saved token is successfully loaded, false otherwise.
{
    // check for saved token, load
    String savedToken = readJWTTokenFromFile();
    if (!savedToken.isEmpty())
    {
        strncpy(token, savedToken.c_str(), sizeof(token) - 1);
        token[sizeof(token) - 1] = '\0'; // Null-terminate the token string
        // strncpy(jwtToken, savedToken.c_str(), sizeof(jwtToken) - 1);
        // jwtToken[sizeof(jwtToken) - 1] = '\0'; // Null-terminate the token string
        gotToken = true;
        Serial.println("Using saved JWT token:");
        Serial.println(token);
        return true;
    }
    else
    {
        return false;
    }
}
References gotToken, readJWTTokenFromFile(), and token.
Referenced by setup().
readJWTTokenFromFile()
String Authentication::readJWTTokenFromFile ()
Reads JWT token from a file stored on LittleFS.
This method attempts to read a JWT token from a file stored on LittleFS (Little File System). If the file exists, it reads the token from the file and returns it. If the file does not exist or if there's any failure during the file system operation, an empty string is returned.
Returns
A string containing the JWT token read from the file, or an empty string if the token couldn't be read.
{
    String jwtToken = "";
    if (LittleFS.begin())
    {
        if (LittleFS.exists(jwtFilePath))
        {
            File file = LittleFS.open(jwtFilePath, "r");
            if (file)
            {
                jwtToken = file.readString();
                file.close();
            }
            else
            {
                Serial.println("no file?");
            }
        }
        else
        {
            Serial.println("file not found on LittleFS");
        }
        LittleFS.end();
    }
    else
    {
        Serial.println("LittlFS Failed to begin");
    }
    return jwtToken;
}
References jwtFilePath, and jwtToken.
Referenced by checkSavedToken(), and Loading::Loading().
saveJWTTokenToFile()
void Authentication::saveJWTTokenToFile (const char * token)
Saves a JWT token to a file on LittleFS.
This method attempts to save a JWT token to a file stored on LittleFS (Little File System). If LittleFS initialization succeeds and the file is successfully created and written, a success message is printed to the Serial monitor. If there's any failure during the file system operation, an error message is printed.
Parameters
token The JWT token to be saved to the file.
{
    if (LittleFS.begin())
    {
        File file = LittleFS.open(jwtFilePath, "w");
        if (file)
        {
            file.print(token);
            file.close();
            Serial.println("JWT token saved to file.");
        }
        else
        {
            Serial.println("couldn't create file?");
        }
        LittleFS.end();
    }
    else{
        Serial.println("Couldn't open Littlefs to write jwt");
    }
}
References jwtFilePath, and token.
Referenced by authenticate().
Member Data Documentation
client
WiFiClient Authentication::client private
WiFi client object.
This object is used for network communication with the server.
Referenced by authenticate().
jwtFilePath
const char* Authentication::jwtFilePath = "/jwt.txt" private
Path to the file storing JWT token.
This string represents the file path of the file storing the JWT token in LittleFS.
Referenced by readJWTTokenFromFile(), and saveJWTTokenToFile().
jwtToken
char Authentication::jwtToken[500] private
Buffer for JWT token.
This buffer stores the JWT token retrieved from LittleFS.
Referenced by Authentication(), and readJWTTokenFromFile().
token
char Authentication::token[500] private
Buffer for JWT token.
This buffer stores the JWT token retrieved from authentication.
Referenced by authenticate(), checkSavedToken(), and saveJWTTokenToFile().
The documentation for this class was generated from the following files:
src/Authentication.h
src/Authentication.cpp